### ISSUE TITLE
Problem with downloading chat of vod

### ISSUE THREAD

**Issue by zdhd122a** [lay295/TwitchDownloader#1062]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I have been using the program for a long time, I have never had such problems with downloading the chat, I tried to download it by giving the admin rights to the script (still did not work), I also tried to download another chat from another vod, the chat was downloaded, the problem is probably only with this id 2148018413
```
C:\Users\jpasf>G:/ze6/TwitchDownloaderCLI-1.53.4-Windows-x64/TwitchDownloaderCLI.exe chatdownload --id 2148018413 --embed-images --bttv=true --ffz=true --stv=true -o chat_2148018413.json
TwitchDownloaderCLI 1.53.4 Copyright (c) lay295 and contributors
Unhandled exception. System.AggregateException: One or more errors occurred. (Value was either too large or too small for an Int32.)
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String )
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
   ```

**Comment by zdhd122a** [comment]
Redownloaded the script, everything worked :)
