### ISSUE TITLE
collision not working

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#1126]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

If output exists crashes:

```
TwitchDownloaderCLI videodownload -u 2162178597 -o 2162178597.mp4 -q best --oauth 1234 --temp-path './temp' --collision Exit
TwitchDownloaderCLI 1.54.7 Copyright (c) lay295 and contributors
Unhandled exception. System.AggregateException: One or more errors occurred. (No destination file was provided, aborting.)
 ---> System.IO.FileNotFoundException: No destination file was provided, aborting.
   at TwitchDownloaderCore.TwitchHelper.ClaimFile(String path, Func`2 fileAlreadyExistsCallback, ITaskLogger logger)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by ScrubN** [comment]
> If output exists crashes

Originally it just returned gracefully, but the WPF task queue needed an exception to properly register as a failure (I hate the design of the task queue)
