### ISSUE TITLE
Can't run in Docker Alpine

### ISSUE THREAD

**Issue by MrBrax** [lay295/TwitchDownloader#120]
```
/usr/local/bin $ ./TwitchDownloaderCLI
/bin/sh: ./TwitchDownloaderCLI: not found
```

Is there some kind of .net/mono runtime i need to install, since i guess it's made in c#? A basic alpine linux install doesn't seem to be able to run this.

**Comment by lay295** [comment]
The .NET Core runtime should be bundled since it's self contained.

![image](https://user-images.githubusercontent.com/1060681/102941686-5a37ac00-4481-11eb-90a8-932674f1161b.png)

I've never really made a docker image, but you'd still need the runtime dependencies.
https://hub.docker.com/_/microsoft-dotnet-runtime-deps
https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies

**Comment by MrBrax** [comment]
installing dotnet via the second script doesn't seem to help, very strange, unless i need to launch it differently somehow

**Comment by lay295** [comment]
Again don't really know anything about docker. Could you just apt-get install all the dependencies? Or include that docker thing somehow? You shouldn't need the dotnet install script for the runtime or sdk. I'm not really sure but I don't think I'll be of much help.

**Comment by MrBrax** [comment]
i don't know the dependencies. i've found some obscure lists with some, but it didn't help
i got the dotnet sdk to work inside docker but it doesn't want to run the executable file
not sure where to go from here

**Comment by MrBrax** [comment]
Installed `gcompat`, now i'm getting a segmentation fault instead.

**Comment by lay295** [comment]
I spun up a Linode and tried to get it working without success. 

Is there a reason you can't use a debian based linux distro?
https://stackoverflow.com/questions/59341750/why-cant-i-run-a-c-program-built-on-alpine-on-ubuntu
https://stackoverflow.com/questions/64996261/alpine-docker-image-with-dotnet-doesnt-see-my-app

It seems I can compile it with linux-musl-x64 and it would work on Alpine, or I could compile it as a portable file and then you could install the runtime on the docker container then run it via the dotnet command. I don't think I will be publishing linux-musl-x64 builds in the future though. Unless I get around to messing with Github Actions.

**Comment by lay295** [comment]
After installing the nuget package StoneCold.SkiaSharp.NativeAssets.AlpineLinux and building with linux-musl-x64 I get this binary. It runs fine until trying to render chat at which point it spits out this error.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontStyle' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory
   at SkiaSharp.SkiaApi.sk_fontstyle_new(Int32 weight, Int32 width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle..ctor(Int32 weight, Int32 width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle..ctor(SKFontStyleWeight weight, SKFontStyleWidth width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle.SKFontStyleStatic..ctor(SKFontStyleWeight weight, SKFontStyleWidth width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFontStyle.get_Normal()
   at TwitchDownloaderCLI.Program.RenderChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Aborted
```

https://drive.google.com/file/d/1P0AtrvJTZ2WSRV5-KEV8lNA33HO1j3EM/view?usp=sharing

**Comment by MrBrax** [comment]
> Is there a reason you can't use a debian based linux distro?
Not really, it's just that alpine is tiny and is commonly used in docker. Probably too much effort to get working.

**Comment by Zibbp** [comment]
If anyone else has this issue and wants to run TwitchDownloader in an Alpine container I got it running by installing the following .net dependencies according to Microsoft's [documentation](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine).
```
apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
```

Here is my `Dockerfile` I created to run TwitchDownloader. I install the .net dependencies and ffmpeg. I also install the Inter font which Twitch uses so the chat render looks the same.

*By default Alpine does not come with standard fonts so you will need to either install the default TwitchDownloader font or specify a custom one when rendering the chat with `--font Inter`. More information can be found on Alpine's [wiki](https://wiki.alpinelinux.org/wiki/Fonts)*

```Dockerfile
FROM alpine:3.13

RUN apk update && apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib ffmpeg

RUN mkdir /root/.fonts

ADD ./Inter.otf /root/.fonts/

WORKDIR /usr/bin

RUN wget https://github.com/lay295/TwitchDownloader/releases/download/1.39.5/TwitchDownloaderCLI-LinuxAlpine-x64.zip && unzip TwitchDownloaderCLI-LinuxAlpine-x64.zip && chmod +x TwitchDownloaderCLI && rm TwitchDownloaderCLI-LinuxAlpine-x64.zip

WORKDIR /opt/app

CMD [ "TwitchDownloaderCLI" ]
```

The final image is about 170 megabytes. The same implementation using a debian:slim image is 500 megabytes.
