### ISSUE TITLE
Error by chat render

### ISSUE THREAD

**Issue by Mirai100** [lay295/TwitchDownloader#1242]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

I am a beginner in Japan
I get an error when I try to download a chat video.
How can I resolve this?
ERROR: The request was canceled because 100 seconds of the configured HttpClient.Timeout has elapsed.

**Comment by Mirai100** [comment]
Add an image
![ゆふな 00_02_41_03 静止画003](https://github.com/user-attachments/assets/9a2a2ca7-2bc7-4aa9-8199-dbfe07a3959e)

**Comment by superbonaci** [comment]
Try with TwitchDownloaderCLI.

**Comment by Mirai100** [comment]
I have tried CLI but it does not work.
I'm a beginner and I don't know where I'm going wrong, so if you don't mind, I'd like to know.

<Error Description>
PS C:\Users\USER\Desktop\TwitchDownloaderCLI-1.55.0-Windows-x64> ./TwitchDownloaderCLI chatrender -i chat.json -o chat.mp4
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Fetching Images [1/2]
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean )
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Modes/RenderChat.cs:line 27
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Program.cs:line 34
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Modes/RenderChat.cs:line 27
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Program.cs:line 34

**Comment by superbonaci** [comment]
Your internet connection is being blocked.

**Comment by superbonaci** [comment]
If you can put the ID I can check it if works for me. you can use https://pastebin.com/ and put expiration date.

**Comment by Mirai100** [comment]
I tried VPN and was able to DL!
Thank you very much for the clear instructions.

**Comment by superbonaci** [comment]
@lay295 @ScrubN the program should not fail if there's no internet.
