### ISSUE TITLE
[Linux][aarch64] TwitchDownloaderCLI: cannot execute binary file: Exec format error (ubuntu)

### ISSUE THREAD

**Issue by 4r1ga70u** [lay295/TwitchDownloader#125]
Hello,

i hope that this is not a doublepost.
i cannot execute the CLI on my Linux system.
unfortunatelyi am a Linux noob. 

Error:
./TwitchDownloaderCLI: cannot execute binary file: Exec format error

I provided execution permission:
-rwxr-xr-x  1 root root 56011567 Dec 21 03:37 TwitchDownloaderCLI*
i download the newest release: 1.38

#Specs:
Linux Khadas 5.9.0-rc2 #0.9.4 SMP PREEMPT Mon Sep 28 16:51:38 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

#lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

i guess the issue is the Architectur aarch64 ?

It  would be awesome if somebody has a hint how to get to running the CLI.

Best Regards
4r1ga70u

**Comment by lay295** [comment]
You would have to download the source code and compile it for ARM64 yourself in the future. 

Not many people are running ARM, so I don't put it out as a release. Maybe in the future when I automate builds I'll have an ARM release. I've tried the ARM version on my raspberry pi 4 a few months ago and it worked.

Here it is compiled for ARM.
https://drive.google.com/file/d/1Yoepa_V2uBi-HIDVSJ0CsuN0gvHene6h/view?usp=sharing

**Comment by 4r1ga70u** [comment]
hi lay295,

thank you for your fast response!

at least i now getting another error.
-bash: /twitchDownloaderCLI: No such file or directory

root@Khadas:~# readelf -a  /twitchDownloaderCLI | grep interpreter
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]

i installed libc6 and libc6-armel
now.
"error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory"

i tried to install some pakages with libstdc++.so.6 but it currently does not fix this issue.

i will check further.....  i maybe need to search for other solution.  :)
Thanks

**Comment by 4r1ga70u** [comment]
OK with sudo aptitude install libstdc++6:armhf and installing many libstdc++6 packages it did run but with follow error:

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser+<>c.<.cctor>b__20_0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at CommandLine.Parser.get_Default()
   at TwitchDownloaderCLI.Program.Main(System.String[])

i researched this message and got to the right side where i could compile the tool with "dotnet"
https://docs.microsoft.com/de-de/dotnet/core/install/linux-ubuntu#2004-

i installed dotnet manualy
https://docs.microsoft.com/de-de/dotnet/core/install/linux-ubuntu#manual-install

then i just run dotnet run on the TwitchDownloaderCLI/ folder and it created the file with many other files.

Currently it looks like its working.
i will test if i manage to download and render chat and reply back again.

**Comment by 4r1ga70u** [comment]
Ok it is current renderung  Chat.
Need check in 3 Hours. 

Here the files that the compiler did create. May it help somebody.
https://mega.nz/file/lZZgWZJb#h9BJ_J4U5_2HL22_8pAQzRENLTWLiCg_B9besBlvdZQ

i dont know how to create just one File.

**Comment by 4r1ga70u** [comment]
rebuilding from source did work. Chat was rendered sucessfully
closing the case

**Comment by lay295** [comment]
Glad you got it sorted out :)
