### ISSUE TITLE
New twitch clip format not working

### ISSUE THREAD

**Issue by DrawTR** [lay295/TwitchDownloader#142]
Twitch seemed to change the format of the clips, adding some numbers and letters at the end. These return in a
`ERROR: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderCore.TwitchHelper.<GetClipInfo>d__3.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderCore\TwitchHelper.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderWPF.PageClipDownload.<btnGetInfo_Click>d__3.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderWPF\PageClipDownload.xaml.cs:line 56
`

**Comment by lay295** [comment]
Perhaps the Twitch API had a problem, all looks good from here and I can download clips.

**Comment by DrawTR** [comment]
Weird. Seems like they changed the format of them, adding some numbers/letters randomly at the end so possible that it broke for a short while
