### ISSUE TITLE
Operation times out

### ISSUE THREAD

**Issue by MycroftHolmes1989** [lay295/TwitchDownloader#176]
Every time I run it, it takes a really long time, and then errors out with this message:
```

Unhandled exception. System.AggregateException: One or more errors occurred. (The operation has timed out.)
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
[1]    7868 abort (core dumped)  TwitchDownloaderCLI -m ChatDownload --id thestreamid -o output.chat
```
OS: Pop OS 20.10

**Comment by lay295** [comment]
Is it still happening? I mean it seems like a connection issue either on your end or on Twitch's end. I probably force the program to render the chat even when it can't retrieve everything but the renders wouldn't be as accurate.

**Comment by MycroftHolmes1989** [comment]
> Is it still happening? I mean it seems like a connection issue either on your end or on Twitch's end.

It happens intermittently. 

>  I probably force the program to render the chat even when it can't retrieve everything but the renders wouldn't be as accurate.

It actually might be a good idea to dump the partial chats. In that case, please add a .partial to the name if the chat is partially rendered. Otherwise it would be difficult to understand if the chat is rendered accurately.

**Comment by goldbattle** [comment]
Closing due to old age, feel free to reopen if still an issue with the newest release.
