### ISSUE TITLE
Exception error when rendering with resolution as 900x367

### ISSUE THREAD

**Issue by chrisle** [lay295/TwitchDownloader#212]
When I attempt to render at 900x367 I get an exception error as soon as it starts to render. But rendering at 1080x422 does not.

* Fails when trying a resolution of 900x367
* I tried both Windows and Mac CLI. Same exception happens on both.
* I have ffmpeg v4.3.1 on both Windows and Mac.

```
$ ./TwitchDownloaderCLI -m ChatRender -i chat.json -h 900 -w 367 --framerate 30 --update-rate 0 --font-size 18 -o chat.mp4
[STATUS] - Fetching Chat Badges
[STATUS] - Fetching Emotes
[STATUS] - Fetching 3rd Party Emotes
[STATUS] - Fetching Cheer Emotes
[STATUS] - Fetching Emojis
[STATUS] - Rendering Comments
[STATUS] - Rendering Video 0% (4h54m20s left)Unhandled exception. System.AggregateException: One or more errors occurred. (Broken pipe)
 ---> System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at TwitchDownloaderCore.ChatRenderer.RenderVideo(ChatRenderOptions renderOptions, Queue`1 finalComments, ChatRoot chatJson, IProgress`1 progress)
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass6_1.<RenderVideoAsync>b__1()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.RenderChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Abort trap: 6
```

* Works if I use the resolution shown in the example. (1080x422)

```
$ ./TwitchDownloaderCLI -m ChatRender -i chat.json -h 1080 -w 422 --framerate 30 --update-rate 0 --font-size 18 -o chat.mp4
[STATUS] - Fetching Chat Badges
[STATUS] - Fetching Emotes
[STATUS] - Fetching 3rd Party Emotes
[STATUS] - Fetching Cheer Emotes
[STATUS] - Fetching Emojis
[STATUS] - Rendering Comments
[STATUS] - Rendering Video 23% (0h17m2s left)
```

**Comment by AndrewDTR** [comment]
Does it work when you try a resolution of **900x367**?

**Comment by lay295** [comment]
Yeah a limitation of a lot of codecs including h264 is that the output resolution height and width need to be even. I have input validation in the GUI version of the program not the command line version though. So I should implement that eventually and give a more understandable error, or maybe just round up to the nearest even resolution.
