### ISSUE TITLE
 System.ArgumentNullException: Value cannot be null. (Parameter 'path')

### ISSUE THREAD

**Issue by dullahan8** [lay295/TwitchDownloader#219]
I tried with less options, swapping the order around, but still not really sure what's wrong. I've definitely downloaded chat renders in the past successfully though.
Happened to me first in verison 1.0.0, then I updated to version 1.39.0 because it still wasn't working.
```
> twitchdownloadercli.exe -m ChatRender --timestamp --embed-emotes -u 1144979452 -o 'video-chatrender'
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at TwitchDownloaderCore.ChatRenderer.ParseJson()
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.RenderChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by lay295** [comment]
I'm very confused with your arguments. I'd suggest taking a look at the example commands at the bottom of [here](https://github.com/lay295/TwitchDownloader/tree/master/TwitchDownloaderCLI#example-commands)

It's probably complaining because you have no input file specified with -i option.

It goes, use ChatDownload to download JSON file. Then use ChatRender to render the JSON file. I'd suggest using the GUI version in release.zip since it looks like you're on Windows.

**Comment by dullahan8** [comment]
Ah! I see, that's what I was doing in correctly. I thought it would download and render in the same step. Thanks, you may close this ticket.

**Comment by dullahan8** [comment]
Also, I see. I was wondering where the GUI was packaged. I was looking for a filename like "*-GUI" and didn't see one so went back to using the CLI. I'll definitely give the GUI a try too!
