### ISSUE TITLE
ERROR: The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#282]
getting error mentioned in the title when trying to download vod/chat (happens with every VOD)

**Comment by mrholshi** [comment]
I am experiencing the same exception. Please find the corresponding stack trace below:

```Unhandled exception. System.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.)
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at TwitchDownloaderCore.TwitchHelper.GetVideoInfo(Int32 videoId)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)```

**Comment by IncorrigiblyBelligerent** [comment]
Same exception here. On Debian Stable.

**Comment by Nutri626** [comment]
its fixed for me, false alarm i guess, gonna close this one

**Comment by lay295** [comment]
It's #251 I gotta migrate off of v5 API and to give warnings Twitch does "blackouts" of APIs they're going to soon deprecate. Today the blackout window was an hour.

https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-i-e-kraken-shutdown-reminder-february-28-2022/36589

I'll try and migrate to just using GQL sometime today.

**Comment by IncorrigiblyBelligerent** [comment]
The v5 API is up now, for the time being

**Comment by Hannah-GBS** [comment]
I'm curious as to whether you'll be *able* to migrate, as Twitch seems specifically uninterested in providing a VOD chat api now.

**Comment by lay295** [comment]
> I'm curious as to whether you'll be _able_ to migrate, as Twitch seems specifically uninterested in providing a VOD chat api now.

I do not think they will ever provide an official API for chat comments. I mean I've always just used their undocumented API and will just keep doing so. I just needed to migrate some requests about getting VOD/Clip info off of kraken.

**Comment by lay295** [comment]
[1.40.5](https://github.com/lay295/TwitchDownloader/releases/tag/1.40.5) doesn't use the Kraken API anymore, so next blackout this version should work. If there are no bug reports for a few days I'll mark it as stable and let people auto update to it.

I moved to GQL instead of Helix because I didn't want people to have to log in, or use some kind of server in my control to proxy requests. Interestingly it looks like TwitchLeecher went the helix approach and now makes users log in, strange. Anyways give it a shot if the regular version isn't working.

**Comment by Nutri626** [comment]
> [1.40.5](https://github.com/lay295/TwitchDownloader/releases/tag/1.40.5) doesn't use the Kraken API anymore, so next blackout this version should work. If there are no bug reports for a few days I'll mark it as stable and let people auto update to it.
> 
> I moved to GQL instead of Helix because I didn't want people to have to log in, or use some kind of server in my control to proxy requests. Interestingly it looks like TwitchLeecher went the helix approach and now makes users log in, strange. Anyways give it a shot if the regular version isn't working.

program simply wont launch

**Comment by lay295** [comment]
Yeah, trying to figure out why... gimme a bit

**Comment by Nutri626** [comment]
> Sorry about that, updated the release.zip and it should work now

yeah its working now, thanks again for fast response & fix as always

**Comment by glubsy** [comment]
Today it started happening again, for any videoId I tried:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The remote server returned an error: (404) Not Found.)
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at TwitchDownloaderCore.TwitchHelper.GetVideoInfo(Int32 videoId)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
[1]    3892450 IOT instruction (core dumped)  TwitchDownloaderCLI -m ChatDownload --id 1286825444 -o 
```

**Comment by mohad12211** [comment]
@glubsy 1.40.7 working with no issues here, did you try to reboot/delete the temp directory?

**Comment by glubsy** [comment]
@mohad12211 indeed, it works now. Might have been a temporary issue on Twitch's side. 

However, I still get the "Object reference not set to an instance of an object" error instead of a proper 404 error when trying to download `--id 1290915475` which is a deleted video so I'm expecting a 404 error (not a big deal I can live with that).
