### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Cowboyserg** [lay295/TwitchDownloader#295]
running the command
```
TwitchDownloaderCLI.exe -m VideoDownload -u 1240475029 -q 1080 --temp-path "C:\tw_temp" --ffmpeg-path "D:\github_d\TwitchDownloaderCLI-Windows-x64\ffmpeg.exe" -o "d:\videos\jam\1240475029\2__4_57_33__0_44_00__1_28_00__dec_22_2021__1240475029.mp4"
```
have output
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot access child value on Newtonsoft.Json.Linq.JValue.)
 ---> System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadVideo(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by mohad12211** [comment]
I can't acess https://www.twitch.tv/videos/1240475029, the vod appears to be deleted. are you sure about the ID?

**Comment by ScrubN** [comment]
If the issue was a removed vod then going forward there is now an explicit error message stating such
