### ISSUE TITLE
Codec is null exception on ChatRender

### ISSUE THREAD

**Issue by SLCH** [lay295/TwitchDownloader#300]
When running the command to render chat, getting an exception:
```
...
[STATUS] - Fetching 3rd Party Emotes
System.ArgumentNullException: Value cannot be null. (Parameter 'codec')
at SkiaSharp.SKBitmap.Decode(SKCodec codec)
...
```

<details>
<summary>Full exception message</summary>

```
TwitchDownloaderCLI -m ChatRender -i chat.json -h 1080 -w 422 --framerate 60 --update-rate 0 --font-size 18 -o chat.mp4

[STATUS] - Fetching Chat Badges
[STATUS] - Fetching Emotes
[STATUS] - Fetching 3rd Party Emotes
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'codec'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'codec')
   at SkiaSharp.SKBitmap.Decode(SKCodec codec)
   at SkiaSharp.SKBitmap.Decode(ReadOnlySpan`1 buffer)
   at SkiaSharp.SKBitmap.Decode(Byte[] buffer)
   at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmotes(Int32 streamerId, String cacheFolder, Emotes embededEmotes, Boolean bttv, Boolean ffz, Boolean stv)
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass6_1.<RenderVideoAsync>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.RenderChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
zsh: IOT instruction (core dumped)  TwitchDownloaderCLI -m ChatRender -i chat.json -h 1080 -w 422  60
```

</details>

<details>
<summary>Using arch btw</summary>

![Screenshot_20220319_230340](https://user-images.githubusercontent.com/2884941/159134993-ee897f48-44df-47f3-802f-40279f6d9412.png)

</details>

Using [latest aur](https://aur.archlinux.org/packages/twitch-downloader-bin) 1.40.7

**Comment by mohad12211** [comment]
can you share the json file?

**Comment by SLCH** [comment]
@mohad12211 sure.

<details>
Vod id: 1418024336

Chat file: https://gist.github.com/SLCH/f8a14c410fcb3a4a9fb74346dfe7ffa2

</details>

**Comment by mohad12211** [comment]
![image](https://user-images.githubusercontent.com/51754973/159136249-974930ae-7734-4e38-81f5-2ee693ac391c.png)
I can't reproduce the issue, maybe try to specify a `--temp-path`?

**Comment by lay295** [comment]
Oh, I still need to fix this issue it looks like. Clear your cache in /tmp/TwitchDownloader and it should work I think. Probably some emote failed to download or the process was stopped sometime mid download and the cached emote is corrupt.

**Comment by SLCH** [comment]
Yep, both setting a new temp folder and clearing default one worked.
Thanks!

PS Had some IO no space error due to executing on wrong drive with almost no space, could have corrupted there.
