### ISSUE TITLE
ERROR: Value cannot be null. (Parameter 'codec')

### ISSUE THREAD

**Issue by HardeQ** [lay295/TwitchDownloader#338]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When i try to render the chat it says "ERROR: Value cannot be null. (Parameter 'codec')". Tried rendering after deleting the temp folder but still doesn't work. System: Windows 11 intel core i3 10300h, geforce gtx 1650ti 16gb ram

**Comment by lay295** [comment]
Can you send a screenshot of your settings?

**Comment by Zibbp** [comment]
Hi, having the same issue with the chat download. Just started occurring this afternoon.

Log of error:
```
[STATUS] - Downloading + Embedding Emotes
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'codec'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'codec')
   at SkiaSharp.SKBitmap.Decode(SKCodec codec)
   at SkiaSharp.SKBitmap.Decode(ReadOnlySpan`1 buffer)
   at SkiaSharp.SKBitmap.Decode(Byte[] buffer)
   at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmotes(Int32 streamerId, String cacheFolder, Emotes embededEmotes, Boolean bttv, Boolean ffz, Boolean stv)
   at TwitchDownloaderCore.ChatDownloader.<>c__DisplayClass3_1.<DownloadAsync>b__1()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

Standard chat download command with a parameter of `--embed-emotes`.

**Comment by HardeQ** [comment]
![image](https://user-images.githubusercontent.com/15715877/181441658-9c93d561-b29e-44d8-816b-2a785715592f.png)
![image](https://user-images.githubusercontent.com/15715877/181441720-f77939ad-8be8-4640-93bf-be9c9fb2478b.png)

**Comment by Zibbp** [comment]
Tried it again this morning and had no issues. I'm guessing one of the emote APIs was having a temporary issues causing the emote fetching for chat download/render to fail? Can anyone else confirm it's working for them?

**Comment by HardeQ** [comment]
Still doesn't work for me.

**Comment by HardeQ** [comment]
Okay i think i know the issue, something is wrong with 7tv emotes option, tried to render without 7tv emotes and it renders.

**Comment by JUGGERNOC** [comment]
> Okay i think i know the issue, something is wrong with 7tv emotes option, tried to render without 7tv emotes and it renders.

yes it is the 7tv emotes, thanks for helping

**Comment by ScrubN** [comment]
The stacktrace reveals that 7TV would have been the issue. Maybe they were testing AVIF? Because the new 7TV API supports only AVIF and WebP and we only *just* started supporting AVIF emotes.
