### ISSUE TITLE
 Unable To Fetch Video Info. Unable to get the video information

### ISSUE THREAD

**Issue by fr1ps** [lay295/TwitchDownloader#453]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

after a 2-3 min of loading app gimme this notification. in the screenshot below
if you insert an id and not a link, nothing changes

![image](https://user-images.githubusercontent.com/63454095/205435765-2398a4bb-20b0-4fdb-a416-9017348c4a58.png)

**Comment by ScrubN** [comment]
Are you able to watch on twitch.tv? I am able to download your video, so I suspect twitch may be blocking your IP address.

![Untitled](https://user-images.githubusercontent.com/72096833/205454084-8087c357-0e40-46b9-9b6a-0ca0ab08fbb8.jpg)

**Comment by fr1ps** [comment]
I can watch video on twitch. I'll try download with VPN. BTW I can download full vod with task queue, but this is inconvenient. I need 1 hour of vod in 10 hour stream.

**Comment by fr1ps** [comment]
> Are you able to watch on twitch.tv? I am able to download your video, so I suspect twitch may be blocking your IP address.
> 
> ![Untitled](https://user-images.githubusercontent.com/72096833/205454084-8087c357-0e40-46b9-9b6a-0ca0ab08fbb8.jpg)

And this problem with all vods, not only with this

**Comment by ScrubN** [comment]
> I can watch video on twitch. I'll try download with VPN. BTW I can download full vod with task queue, but this is inconvenient. I need 1 hour of vod in 10 hour stream.

Interesting. Maybe only Twitch GQL is blocking your IP.

Also task queue will use the quality, crop, and thread settings on the download page.

**Comment by fr1ps** [comment]
> 

![image](https://user-images.githubusercontent.com/63454095/205481797-2ef81d8a-2230-40fc-b472-92e6e854559e.png)
u are right. with vpn all working correct, tnx bro

**Comment by ScrubN** [comment]
Looking online, it seems it's probably that itop is secretly not connecting. You can test that by searching "what is my ip" before and after connecting to itop. Honestly, it looks like the software is built just to harvest data from its users like most other free vpns.

**Comment by fr1ps** [comment]
> Looking online, it seems it's probably that itop is secretly not connecting. You can test that by searching "what is my ip" before and after connecting to itop. Honestly, it looks like the software is built just to harvest data from its users like most other free vpns.

![image](https://user-images.githubusercontent.com/63454095/205935035-2d7e0954-9bc7-4067-ba88-f0a3b9a42a14.png)

**Comment by fr1ps** [comment]
I found that after rebooting pc program working correct, without vpn....

**Comment by ScrubN** [comment]
If you need further assistance with this feel free to reopen the issue

**Comment by hellishvictor** [comment]
> ![image](https://user-images.githubusercontent.com/63454095/205435765-2398a4bb-20b0-4fdb-a416-9017348c4a58.png)

Here I get too that message, I don't have problems at all watching video/vods, downloading them with [yt-dlp](https://github.com/yt-dlp/yt-dlp) or the chats with [chat-downloader](https://github.com/xenova/chat-downloader).

I've tried the CLI and I get the following:
`Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be
established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of err
ors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken , ExceptionDispatchInfo )
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions )
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boole
an )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , Cancellati
onToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToke
n )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationT
oken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean ,
Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , Cancellat
ionTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at TwitchDownloaderCore.TwitchHelper.GetClipLinks(String clipId)
   at TwitchDownloaderCore.ClipDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadClip.Download(ClipDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
`
Btw, I'm on Win7 SP1 x64.
Cheers.

**Comment by hellishvictor** [comment]
> ![image](https://user-images.githubusercontent.com/63454095/205435765-2398a4bb-20b0-4fdb-a416-9017348c4a58.png)

Here I get too that message, I don't have problems at all watching video/vods, downloading them with [yt-dlp](https://github.com/yt-dlp/yt-dlp) or the chats with [chat-downloader](https://github.com/xenova/chat-downloader).

I've tried the CLI and I get the following:
`
Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be
established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of err
ors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken , ExceptionDispatchInfo )
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions )
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boole
an )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , Cancellati
onToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToke
n )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationT
oken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean ,
Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , Cancellat
ionTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at TwitchDownloaderCore.TwitchHelper.GetClipLinks(String clipId)
   at TwitchDownloaderCore.ClipDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadClip.Download(ClipDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
`

Btw, I'm on Win7 SP1 x64.
Cheers.

**Comment by hellishvictor** [comment]
Here I get that message too:
`Unable to get info: Unable to get video information. Please make sure the Link/ID is correct and try again.`

 I don't have problems at all watching video/vods, downloading them with [yt-dlp](https://github.com/yt-dlp/yt-dlp) or the chats with [chat-downloader](https://github.com/xenova/chat-downloader).

I've tried the CLI for download a clip and I get the following:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be
established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of err
ors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken , ExceptionDispatchInfo )
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions )
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boole
an )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMe
ssage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , Cancellati
onToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToke
n )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationT
oken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean ,
Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , Cancellat
ionTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at TwitchDownloaderCore.TwitchHelper.GetClipLinks(String clipId)
   at TwitchDownloaderCore.ClipDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadClip.Download(ClipDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)

```

Btw, I'm on Win7 SP1 x64.
Cheers.
