### ISSUE TITLE
Linux CLI Chat Render - Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by Zibbp** [lay295/TwitchDownloader#481]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Hi,
I'm attempting to render a chat ([download-111mb](https://transfer.sh/fk4MI0/tdl-chat.json), id: `1682060475`) using the Alpine x86 CLI (latest version) and I'm repeatedly receiving the following error. 
```
[STATUS] - Rendering Video: 62% (0h55m47s Elapsed | 0h33m51s Remaining)Segmentation fault (core dumped)
```
The error occurs at exactly 62% every time, leading me to believe there is something wrong with rendering the video. This error *only* occurs using the Alpine CLI. Both the Windows GUI and standard x86 CLI renders this chat without issue. I've rendered chats without issue using the latest release, only this one is causing issues.

Is there a more verbose output or debug level to set that will provide more information of the crash? I saw in the documentation there is a `--verbose-ffmpeg` chatrender argument, but seems to no longer be a valid argument.

I do not know much about c# and .net but doing some research on gathering more information I was able to use `dotnet-trace` and get a `.nettrace` file of when the error occurred, let me know if that is of any use.

**Comment by ScrubN** [comment]
> The error occurs at exactly 62% every time, leading me to believe there is something wrong with rendering the video. This error _only_ occurs using the Alpine CLI. Both the Windows GUI and standard x86 CLI renders this chat without issue. I've rendered chats without issue using the latest release, only this one is causing issues.
> 
> Is there a more verbose output or debug level to set that will provide more information of the crash? I saw in the documentation there is a `--verbose-ffmpeg` chatrender argument, but seems to no longer be a valid argument.

`--verbose-ffmpeg` will be a valid option in 1.51.2

> I do not know much about c# and .net but doing some research on gathering more information I was able to use `dotnet-trace` and get a `.nettrace` file of when the error occurred, let me know if that is of any use.

That would be very helpful

**Comment by Zibbp** [comment]
> That would be very helpful

Appended `.txt` to the filename to allow a Github upload. [TwitchDownloaderCLI_20221219_115340.nettrace.txt](https://github.com/lay295/TwitchDownloader/files/10263289/TwitchDownloaderCLI_20221219_115340.nettrace.txt). The capture starts a few seconds before the error occurs.

Is there a way to enable a CLI equivalent of "Verbose Errors" from the GUI version?

**Comment by ScrubN** [comment]
> Is there a way to enable a CLI equivalent of "Verbose Errors" from the GUI version?

The CLI already displays full stack traces while the GUI cleans them up for non-technical users which is why I added the 'Verbose Errors" option to get the full stack trace.

**Comment by ScrubN** [comment]
Just had a thought, its possible the segfault is something we just fixed but haven't released yet. Can you try this CI workflow build? https://github.com/lay295/TwitchDownloader/suites/9940640582/artifacts/481284831

**Comment by ScrubN** [comment]
Unfortunately it seems the .nettrace file is corrupted :(

```
Started: Opening TwitchDownloaderCLI_20221219_115340.nettrace
Creating ETLX file C:\Users\ScrubN\AppData\Local\Temp\PerfView\TwitchDownloaderCLI_20221219_115340_ce0fb06d.etlx from C:\Users\ScrubN\Desktop\TwitchDownloaderCLI_20221219_115340.nettrace
[Opening a log file of size 0 MB.]
[ELAPSED  0 seconds.     READ    131,072 events.     TIMESTAMP  12,004ms.     WRITTEN    21MB.     ]
[ERROR: processing events ****]
***** Consider using /ContinueOnError to ignore the bad part of the trace.  *****
Error: Exception EventPipe conversion: System.Exception: Read past end of stream.
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadByte()
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CopyRawEvents(TraceEventDispatcher rawEvents, IStreamWriter writer)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.<>c__DisplayClass120_0.<FastSerialization.IFastSerializable.ToStream>b__0()
   at FastSerialization.DeferedRegion.Write(Serializer serializer, Action toStream)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.ToStream(Serializer serializer)
   at FastSerialization.Serializer.WriteObjectData(IFastSerializable obj, Tags beginTag)
   at FastSerialization.Serializer.WriteObjectRef(IFastSerializable obj, Boolean defered)
   at FastSerialization.Serializer..ctor(IStreamWriter writer, IFastSerializable entryObject)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeEventSources(TraceEventDispatcher source, String etlxFilePath, TraceLogOptions options)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
   at PerfView.EventPipePerfViewData.GetTraceLog(TextWriter log, Action`3 onLostEvents)
[Error: exception while opening EventPipe data.]
Completed: Opening TwitchDownloaderCLI_20221219_115340.nettrace   (Elapsed Time: 0.351 sec)
```

**Comment by ScrubN** [comment]
I've spent a bit trying to read the dottrace file in PerfView but nearly everything is marked as happening externally so I think it's better that I make you a custom debug build that logs *everything*.

(Anything that says external or has `!?` in the name is external)
![TwitchDownloaderCLI_20221219_115340 flameGraph1](https://user-images.githubusercontent.com/72096833/208556538-7c6a18ca-44a2-45c6-a8c0-30a479d9ee6a.png)

**Comment by ScrubN** [comment]
The custom build is ready: https://github.com/ScrubN/TwitchDownloader/releases/tag/Debug

**Comment by ScrubN** [comment]
Also call me crazy but I don't think that RTL message was rendered correctly. @mohad12211 
![image](https://user-images.githubusercontent.com/72096833/208578572-4ce7a5d5-a315-4e97-aa5d-a9316a9f354f.png)

**Comment by mohad12211** [comment]
> Also call me crazy but I don't think that RTL message was rendered correctly. @mohad12211 
> 
> ![image](https://user-images.githubusercontent.com/72096833/208578572-4ce7a5d5-a315-4e97-aa5d-a9316a9f354f.png)
> 
> 

Yeah looks completely wrong

**Comment by Zibbp** [comment]
I installed a few of the [Noto](https://fonts.google.com/noto/specimen/Noto+Sans) fonts suggested on the [Alpine wiki](https://wiki.alpinelinux.org/wiki/Fonts), and it's working just fine now.

Thanks for the help ScrubN!

I see you created another issue for the RTL message render so I am going to close this issue.

**Comment by ScrubN** [comment]
> I installed a few of the [Noto](https://fonts.google.com/noto/specimen/Noto+Sans) fonts suggested on the [Alpine wiki](https://wiki.alpinelinux.org/wiki/Fonts), and it's working just fine now.

I'll be adding this to the README to help future Alpine users and any other distros that may have the same problem.
