### ISSUE TITLE
Access to the path is denied.

### ISSUE THREAD

**Issue by pablo-01** [lay295/TwitchDownloader#542]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Application does not start.

```
System.UnauthorizedAccessException
  HResult=0x80070005
  Message=Access to the path 'C:\Users\PC\Desktop\ttvdl\TwitchDownloader\TwitchDownloaderWPF\bin\x64\Debug\net6.0-windows\Themes\README.txt' is denied.
  Source=System.Private.CoreLib
  StackTrace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at TwitchDownloader.Tools.DefaultThemeService.WriteIncludedThemes() in C:\Users\PC\Desktop\ttvdl\TwitchDownloader\TwitchDownloaderWPF\Services\DefaultThemeService.cs:line 24
   at TwitchDownloader.Tools.ThemeService..ctor(App app, WindowsThemeService windowsThemeService) in C:\Users\PC\Desktop\ttvdl\TwitchDownloader\TwitchDownloaderWPF\Services\ThemeService.cs:line 30
   at TwitchDownloaderWPF.App.OnStartup(StartupEventArgs e) in C:\Users\PC\Desktop\ttvdl\TwitchDownloader\TwitchDownloaderWPF\App.xaml.cs:line 26
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by ScrubN** [comment]
Looks like you're building from source? Make sure the account you're running it from has access to the execution directory

**Comment by pablo-01** [comment]
> 

I have also ran it from already built downloaded from the release links with same result.

**Comment by ScrubN** [comment]
Interesting. It sounds like your user account is locked down.

If the program doesn't have access to extract the themes then it probably won't be able to save any downloads anyways.

**Comment by pablo-01** [comment]
> 

Strange as it's me personal PC where I do have write access to pretty much anywhere.

**Comment by ScrubN** [comment]
Do you have any restrictions set in the windows "privacy" settings regarding file system access? Maybe it's possible that your machine refuses to give relative/envvar path access, only absolute paths?

**Comment by pablo-01** [comment]
Avast Antivirus is causing that.
