### ISSUE TITLE
Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by MarkGelo** [lay295/TwitchDownloader#605]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Encountered these errors from downloading the chat from old vods such as 325392389 and 328421817.

![image](https://user-images.githubusercontent.com/28793709/224570717-17ca5428-d829-49e1-91a2-fd1db398387c.png)

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchDownloaderCore.ChatDownloader.ConvertComments(CommentVideo video)
   at TwitchDownloaderCore.ChatDownloader.DownloadSection(Double videoStart, Double videoEnd, String videoId, SortedSet`1 comments, Object commentLock, IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by ScrubN** [comment]
For some dumb reason the response comment collection can be null. Seems like I fixed it?
