### ISSUE TITLE
I got "Downloading + Embedding ImagesUnhandled exception." when trying to download a chat JSON with all images embedded.

### ISSUE THREAD

**Issue by YousufSSyed** [lay295/TwitchDownloader#641]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I'm using an M1 MacBookAir with `TwitchDownloaderCLI-1.52.2-MacOS-x64` When I run this command:

```
./TwitchDownloaderCLI chatdownload --embed-images --bttv=true --ffz=true --stv=true -u 1778287275 -o "Quick Dev Stream.json" 
```

I get this output:

```
[STATUS] - Downloading 96%
[STATUS] - Downloading + Embedding ImagesUnhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'collection'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
   at System.Collections.Generic.List`1.InsertRange(Int32 , IEnumerable`1 )
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 )
   at TwitchDownloaderCore.TwitchHelper.GetBttvEmoteData(Int32 streamerId, List`1 bttvResponse)
   at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmoteData(Int32 streamerId, Boolean getBttv, Boolean getFfz, Boolean getStv, Boolean allowUnlistedEmotes, CancellationToken cancellationToken)
   at TwitchDownloaderCore.TwitchHelper.GetThirdPartyEmotes(List`1 comments, Int32 streamerId, String cacheFolder, EmbeddedData embeddedData, Boolean bttv, Boolean ffz, Boolean stv, Boolean allowUnlistedEmotes, Boolean offline, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
[1]    43604 abort      ./TwitchDownloaderCLI chatdownload --embed-images --bttv=true --ffz=true  -u
```

However this command worked: `./TwitchDownloaderCLI chatdownload -E -u 1778287275 -o "Quick Dev Stream.txt"`. But I want the other one to make sure I always get all images and emojis.

Also, shouldn't an M1 version compiled as well for releases, as well as a universal version?

**Comment by ScrubN** [comment]
Duplicate #622, it was resolved in #623 for the next release.
You can either use the previous version or use a workflow build from after it was patched: [github.com/lay295/TwitchDownloader/actions/runs/4518437439](https://github.com/lay295/TwitchDownloader/actions/runs/4518437439)

> Also, shouldn't an M1 version compiled as well for releases, as well as a universal version?

Unfortunately no one with an Apple M device has compiled an M-native binary, confirmed it works, and shared their configuration. If you know how to configure C# compilation for M devices and find success, a PR would be very much appreciated!
