### ISSUE TITLE
System.NotImplementedException in Tools.HighlightMessage.SplitSubComment

### ISSUE THREAD

**Issue by andymcblane** [lay295/TwitchDownloader#664]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When rendering VOD ID 1052527102 or 1052447809 I hit this stack trace. 

```

[STATUS] - Rendering Video: 29% (0h4m6s Elapsed | 0h10m4s Remaining)
[STATUS] - Rendering Video: 29% (0h4m7s Elapsed | 0h10m3s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (This should not be possible.)
 ---> System.NotImplementedException: This should not be possible.
   at TwitchDownloaderCore.Tools.HighlightMessage.SplitSubComment(Comment comment)
   at TwitchDownloaderCore.ChatRenderer.DrawSubscribeMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, Point& drawPos, Point defaultPos, SKBitmap highlightIcon, Point iconPoint)
   at TwitchDownloaderCore.ChatRenderer.DrawAccentedMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, HighlightType highlightType, HighlightMessage highlightIcons, Point& drawPos, Point defaultPos)
   at TwitchDownloaderCore.ChatRenderer.GenerateCommentSection(Int32 commentIndex, Int32 sectionDefaultYPos, HighlightMessage highlightIcons)
   at TwitchDownloaderCore.ChatRenderer.GenerateUpdateFrame(Int32 currentTick, Int32 sectionDefaultYPos, HighlightMessage highlightIcons, UpdateFrame lastUpdate)
   at TwitchDownloaderCore.ChatRenderer.RenderVideoSection(Int32 startTick, Int32 endTick, FfmpegProcess ffmpegProcess, FfmpegProcess maskProcess, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass25_0.<RenderVideoAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)

```

I have verified using v1.52.4 (GUI)

Looks like a missing emote from a cursory glace at the code but I have not dove in the JSON to explore the chat message :) 

Thanks for the amazing tool!

**Comment by andymcblane** [comment]
The issue has to do with the fragments of the Subscribe message.

This is from `TwitchDownloaderCLI.exe chatdownload` output 

```
"fragments": [
    {
        "text": "Leela3001 subscribed at Tier 1. They've subscribed for 7 months, currently on a 7 month streak! ",
        "emoticon": null
    },
    {    
        "text": "@Kitboga",
        "emoticon": null
    },
    {
        "text": " I am not feeling that great today. please make me laugh and feel l better today",
        "emoticon": null
    }
],

```

I suspect the @Kitboga has caused it to be broken down into multiple fragments. The VOD is from 2021 so maybe Twitch have updated the format since then, hence this issue only coming up now. 


This code expects an emote in fragment[1] - https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCore/Tools/HighlightMessage.cs#L248


I have verified that this structure is coming from the GraphQL response

Thanks!

**Comment by ScrubN** [comment]
When I wrote the code I only knew of fragments being separated by emotes, not mentions (in older chats). It's a good thing I put an exception there rather than relying on noticing it render incorrectly.
