### ISSUE TITLE
Potential API change for loading twitch emotes breaks download and/or render

### ISSUE THREAD

**Issue by Hyumiris** [lay295/TwitchDownloader#671]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Since at most 24h chatdownload fails during `[STATUS] - Downloading + Embedding Images`. This occurs even for vods that i downloaded successfully yesterday.

I assume that its (at least) the twitch emotes since this command fails:
`chatdownload --id 1789381107 -E --bttv false --ffz false --stv false -o onlyTwitchEmotes.json`
When not loading emotes it works:
`chatdownload --id 1789381107 -o noEmotes.json`
But then the render fails, except when using `--offline`.

Error message looks like this:
```
% TwitchDownloaderCLI chatdownload --id 1789381107 -E --bttv false --ffz false --stv false -o onlyTwitchEmotes.json
[STATUS] - Downloading 99%
[STATUS] - Downloading + Embedding ImagesUnhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean )
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
zsh: abort      TwitchDownloaderCLI chatdownload --id 1789381107 -E --bttv false --ffz false 
```

**Comment by ScrubN** [comment]
As far as I can tell, the emoticons v2 cdn is not being deprecated. Something interesting though is that this seems to be the same as #578.

**Comment by Hyumiris** [comment]
And just like that issue it seems to have fixed itself for me too. Maybe that endpoint was not reachable under ipv6 for a while. This has caused some issues for me a while back. But anyway, issue is gone now.
