### ISSUE TITLE
Failed to finalize video (code 1)

### ISSUE THREAD

**Issue by Hunam6** [lay295/TwitchDownloader#678]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I'm on MacOS Ventura 13.2.1.
```
[STATUS] - Fetching Video Info [1/4]
[STATUS] - Downloading 100% [2/4]
[STATUS] - Combining Parts 100% [3/4]
[STATUS] - Finalizing Video 0% [4/4]
[LOG] - Failed to finalize video (code 1), retrying in 10 seconds...

[LOG] - Failed to finalize video (code 1), retrying in 10 seconds...
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to finalize video. The download cache has not been cleared and can be found at /var/folders/xc/vnn2dtr95kl2x744xj_r2vt80000gn/T/TwitchDownloader/1786647944_1681822179812 along with a log file.)
 ---> System.Exception: Failed to finalize video. The download cache has not been cleared and can be found at /var/folders/xc/vnn2dtr95kl2x744xj_r2vt80000gn/T/TwitchDownloader/1786647944_1681822179812 along with a log file.
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
zsh: abort      ./TwitchDownloaderCLI videodownload -u https://www.twitch.tv/videos/178664794
```

**Comment by ScrubN** [comment]
If you could provide the log file that would help immensely!

**Comment by SamuelMCQ** [comment]
I have the same error, can I post my log here or should I make a new issue?

**Comment by Hunam6** [comment]
@phucvi95 my output is only `.`

@SamuelMCQ yes post it here please, the VOD I wanted to download got deleted from Twitch, not sure I can reproduce again

**Comment by ScrubN** [comment]
> I have the same error, can I post my log here or should I make a new issue?

Anyone with a log from a failed finalization, please post the log

**Comment by quiet23** [comment]
In my case it was indeed missing quotes in -o parameter:
`TwitchDownloaderCLI videodownload -u 1804998252 -o Ande vs Hammer on CPQ Bullet 2023.mp4 -b 3718 -e 3816 -t 1`
[ffmpegLog.txt](https://github.com/lay295/TwitchDownloader/files/11347485/ffmpegLog.txt)
Linux Mint 21.1
But I think it would be nice if TwitchDownloader had processed the exception and given meaningful error message.

**Comment by ScrubN** [comment]
> In my case it was indeed missing quotes in -o parameter: `TwitchDownloaderCLI videodownload -u 1804998252 -o Ande vs Hammer on CPQ Bullet 2023.mp4 -b 3718 -e 3816 -t 1` [ffmpegLog.txt](https://github.com/lay295/TwitchDownloader/files/11347485/ffmpegLog.txt) Linux Mint 21.1 But I think it would be nice if TwitchDownloader had processed the exception and given meaningful error message.

Your specific issue is that you need to wrap output path in single or double quotes because there are spaces. 
`TwitchDownloaderCLI videodownload -u 1804998252 -o "Ande vs Hammer on CPQ Bullet 2023.mp4" -b 3718 -e 3816 -t 1`

**Comment by quiet23** [comment]
> > In my case it was indeed missing quotes in -o parameter: `TwitchDownloaderCLI videodownload -u 1804998252 -o Ande vs Hammer on CPQ Bullet 2023.mp4 -b 3718 -e 3816 -t 1` [ffmpegLog.txt](https://github.com/lay295/TwitchDownloader/files/11347485/ffmpegLog.txt) Linux Mint 21.1 But I think it would be nice if TwitchDownloader had processed the exception and given meaningful error message.
> 
> Your specific issue is that you need to wrap output path in single or double quotes because there are spaces. `TwitchDownloaderCLI videodownload -u 1804998252 -o "Ande vs Hammer on CPQ Bullet 2023.mp4" -b 3718 -e 3816 -t 1`
I know, thank you. I mentioned that in the first sentence. It worked. But it would be nice to have the app to report something meaningful instead of unhandled exception track trace.
