### ISSUE TITLE
System.ArgumentOutOfRangeException gets thrown when using the chatrender feature

### ISSUE THREAD

**Issue by MrAndeos** [lay295/TwitchDownloader#686]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

When I try to download & render chat, like that:
`TwitchDownloaderCLI.exe chatdownload --id %vodid% -o ..\%vodid%_chat.json`
`TwitchDownloaderCLI.exe chatrender -i ..\%vodid%_chat.json -h 1080 -w 422 --framerate 30 --update-rate 0 --font-size 18 --temp-path D:\twitch-leecher-temp -o ..\%vodid%_chat.mp4`

I get the following exception (sorry for the excessive line terminators, it's copied from Windows 7 cmd):
```
[STATUS] - Downloading 98%
[STATUS] - Backfilling commenter info
[STATUS] - Writing output file
[STATUS] - Fetching Images [1/2]
[STATUS] - Rendering Video: 0% (0h0m0s Elapsed | 0h35m25s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (capacity was less than the current size. (Parameter 'value')))
 ---> System.AggregateException: One or more errors occurred. (capacity was less than the current size. (Parameter 'value'))
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.Collections.Generic.List`1.set_Capacity(Int32 )
   at System.Collections.Generic.List`1.Grow(Int32 )
   at System.Collections.Generic.List`1.AddWithResize(T )
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass46_1.<DrawEmojiMessage>b__1(SingleEmoji emoji)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput&, Int32& )
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object )
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object )
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean )
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState , PartitionedStream`2 , TaskScheduler )
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 , Boolean , ParallelMergeOptions , TaskScheduler , Boolean , CancellationState , Int32 )
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 )
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 , IPartitionedStreamRecipient`1 , Boolean , QuerySettings )
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 )
   at System.Linq.Parallel.WhereQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 , IPartitionedStreamRecipient`1 , Boolean , QuerySettings )
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 )
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 )
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 )
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 )
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 , Boolean , Boolean , QuerySettings )
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 , Action`1)
   at TwitchDownloaderCore.ChatRenderer.DrawEmojiMessage(List`1 sectionImages, List`1 emotePositionList, Point& drawPos, Point defaultPos, Int32 bitsCount, String fragmentString, Boolean highlightWords)
   at TwitchDownloaderCore.ChatRenderer.DrawFragmentPart(List`1 sectionImages, List`1 emotePositionList, Point& drawPos, Point defaultPos, Int32 bitsCount, String fragmentPart, Boolean highlightWords, Boolean skipThird, Boolean skipEmoji, Boolean skipNonFont)
   at TwitchDownloaderCore.ChatRenderer.DrawMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, Boolean highlightWords, Point& drawPos, Point defaultPos)
   at TwitchDownloaderCore.ChatRenderer.DrawNonAccentedMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, Boolean highlightWords, Point& drawPos, Point& defaultPos)
   at TwitchDownloaderCore.ChatRenderer.GenerateCommentSection(Int32 commentIndex, Int32 sectionDefaultYPos, HighlightMessage highlightIcons)
   at TwitchDownloaderCore.ChatRenderer.GenerateUpdateFrame(Int32 currentTick, Int32 sectionDefaultYPos, HighlightMessage highlightIcons, UpdateFrame lastUpdate)
   at TwitchDownloaderCore.ChatRenderer.RenderVideoSection(Int32 startTick, Int32 endTick, FfmpegProcess ffmpegProcess, FfmpegProcess maskProcess, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass25_0.<RenderVideoAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by ScrubN** [comment]
I think the issue was caused by the use of a non thread-safe list. I'll switch it to a ConcurrentBag<> and should hopefully fix it.

**Comment by ScrubN** [comment]
Until 1.52.6 is out, you can use a workflow build from the patch: https://github.com/lay295/TwitchDownloader/actions/runs/4751036940
