### ISSUE TITLE
ERROR: startIndex cannot be larger than length of string. (Parameter 'startIndex')

### ISSUE THREAD

**Issue by andymcblane** [lay295/TwitchDownloader#701]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

I am hitting this exception in ChatRenderer for VOD IDs 541916391, 541604938

```
[STATUS] - Rendering Video: 3% (0h1m38s Elapsed | 0h52m29s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (startIndex cannot be larger than length of string. (Parameter 'startIndex'))
 ---> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 , Int32 )
   at TwitchDownloaderCore.ChatRenderer.DrawSubscribeMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, Point& drawPos, Point defaultPos, SKBitmap highlightIcon, Point iconPoint)
   at TwitchDownloaderCore.ChatRenderer.DrawAccentedMessage(Comment comment, List`1 sectionImages, List`1 emotePositionList, HighlightType highlightType, HighlightMessage highlightIcons, Point& drawPos, Point defaultPos)
   at TwitchDownloaderCore.ChatRenderer.GenerateCommentSection(Int32 commentIndex, Int32 sectionDefaultYPos, HighlightMessage highlightIcons)
   at TwitchDownloaderCore.ChatRenderer.GenerateUpdateFrame(Int32 currentTick, Int32 sectionDefaultYPos, HighlightMessage highlightIcons, UpdateFrame lastUpdate)
   at TwitchDownloaderCore.ChatRenderer.RenderVideoSection(Int32 startTick, Int32 endTick, FfmpegProcess ffmpegProcess, FfmpegProcess maskProcess, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.<>c__DisplayClass25_0.<RenderVideoAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

I have not yet had a chance to dig into the specifics but will do so in next few days

**Comment by andymcblane** [comment]
Legend thanks! :)
