### ISSUE TITLE
Random crashes on CLI chat download

### ISSUE THREAD

**Issue by Tristar7** [lay295/TwitchDownloader#723]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Occuring randomly

```
Application: TwitchDownloaderCLI.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchDownloaderCore.ChatDownloader.ConvertComments(CommentVideo video)
   at TwitchDownloaderCore.ChatDownloader.DownloadSection(Double videoStart, Double videoEnd, String videoId, SortedSet`1 comments, Object commentLock, IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

works when retrying same vod

and another

```
Application: TwitchDownloaderCLI.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..)
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter )
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter , Memory`1 )
   at System.Net.Http.HttpConnection.FillAsync(Boolean )
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 , CancellationToken )
   at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream , CancellationToken , Boolean )
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream , JsonTypeInfo , CancellationToken )
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent , Encoding , JsonSerializerOptions , CancellationToken )
   at TwitchDownloaderCore.ChatDownloader.DownloadSection(Double videoStart, Double videoEnd, String videoId, SortedSet`1 comments, Object commentLock, IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

looks like it should just retry here

**Comment by teadrinker2015** [comment]
I have a similar problem randomly occurring.
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)    
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchDownloaderCore.TwitchHelper.GetOrGenerateVideoChapters(Int32 videoId, VideoInfo videoInfo)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```
Seems related to downloading, acording to previous posts.

**Comment by ScrubN** [comment]
> I have a similar problem randomly occurring.
> 
> ```
> Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)    
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at TwitchDownloaderCore.TwitchHelper.GetOrGenerateVideoChapters(Int32 videoId, VideoInfo videoInfo)
>    at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
>    at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
>    at System.Threading.Tasks.Task.Wait()
>    at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at TwitchDownloaderCLI.Program.Main(String[] args)
> ```
> 
> Seems related to downloading, acording to previous posts.

Your issue is not related to the original issue, please post your vod ID.

**Comment by teadrinker2015** [comment]
```powershell
TwitchDownloaderCLI.exe chatdownload -E --id 1955634553 --chat-connections 1 -o '10／20 【 #ストグラ 】APEXカスタム！めいかちゃん・ボアちゃんと！【 #輝海まりな 】 [1955634553].html'
```
```powershell
TwitchDownloaderCLI.exe chatdownload -E --id 1973514736 -o '10／10 【 #ストグラ 】Day84・お花屋さん❁【 #淀川てるみ #輝海まりな 】 [1973514736].html'
```
Test with or without `--chat-connections 1`, both encountered the same problem, after 5 to 20 downloads.
Qoutes are added manually. The spaces escaping is actually handled by nodejs `execFile()`.

**Comment by ScrubN** [comment]
Unfortunately I'm unable to reproduce your issue locally, and I'm unsure about what exactly could have been null.

**Comment by jmSfernandes** [comment]
Hey I am also facing the same issue:
I made a custom version of the CLI to catch the aggregated exception and print each exception before throwing...
But unfortunately, the log is just too small to understand where the problem is.

```
Error downloading chat for 'https://www.twitch.tv/videos/2001076222', errors: Unhandled exception. System.Exception:
--
System.NullReferenceException: Object reference not set to an instance of an object.
at TwitchDownloaderCore.ChatDownloader.DownloadSection(Double videoStart, Double videoEnd, String videoId, IProgress`1 progress, ChatFormat format, CancellationToken cancellationToken)
at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
at TwitchDownloaderCLI.Program.Main(String[] args)
```
I also had one which pointed out to GetOrGenerateVideoChapters, as pointed out by @teadrinker2015... And I think it is in fact related to the same issue.
```
Error downloading chat for 'https://www.twitch.tv/videos/1254003669', errors: Unhandled exception. System.Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchDownloaderCore.TwitchHelper.GetOrGenerateVideoChapters(Int32 videoId, VideoInfo videoInfo)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions)
   ...
```

The bug is very randomic and it is hard to reproduce, and running the command twice just works... so I'm incline to think that is something related with the Twitch API response... 🤔 

I will try to build the app on debug mode or something to see if I can get more specific logs out of the runtime...

**Comment by jmSfernandes** [comment]
Update: I tried it out and finally got the same error.
```shell 
#command ran:
TwitchDownloaderCLI chatdownload -E --chat-connections 200 --timestamp-format Utc -u https://www.twitch.tv/videos/2003502167 -o /tmp/tmpjqj5ppx_/chat.txt

```
```shell
Error downloading chat for 'https://www.twitch.tv/videos/2003502167', errors: Unhandled exception. System.Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
at TwitchDownloaderCore.TwitchHelper.GetOrGenerateVideoChapters(Int32 videoId, VideoInfo videoInfo) in C:\Users\user\RiderProjects\TwitchDownloader\TwitchDownloaderCore\TwitchHelper.cs:line 939
at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\user\RiderProjects\TwitchDownloader\TwitchDownloaderCore\ChatDownloader.cs:line 291
at TwitchDownloaderCLI.Modes.DownloadChat.Download(ChatDownloadArgs inputOptions) in C:\Users\user\RiderProjects\TwitchDownloader\TwitchDownloaderCLI\Modes\DownloadChat.cs:line 30
at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
at TwitchDownloaderCLI.Program.Main(String[] args) in C:\Users\user\RiderProjects\TwitchDownloader\TwitchDownloaderCLI\Program.cs:line 33
```
Line 939 on my code is this one 
![image](https://github.com/lay295/TwitchDownloader/assets/45356734/b353900d-1493-4921-80bf-59687cb2ef40)

Makes sense that the error is on this line, since we are trying to access a lot of nested objects but not checking for nullity.
However, the weird part is that if I run the exact same command it works without a problem at the second time.
So I tend to think this is a problem related with the communication with Twitch... 

From what I could gather these chapters are not really used anywhere apart from being serialized when the response is saved in Json (I believe for additional info) (e.g., In my use case, I think I don't need these `VideoChapters`... )
I could make a PR to solve this with the nullity checks... but any advice on how to proceed with this @ScrubN 

**Note:** this is only part of my problem since I still have another NullPointException in the download but I could not replicate it until now. But it might be related after all since it could be when the code checks for some of the parameters in the videoChapters.

**Comment by ScrubN** [comment]
> From what I could gather these chapters are not really used anywhere apart from being serialized when the response is saved in Json (I believe for additional info) (e.g., In my use case, I think I don't need these `VideoChapters`... )

The video chapters are serialized to chat JSONs, however they are also used for encoding VOD chapters.

> I could make a PR to solve this with the nullity checks... but any advice on how to proceed with this @ScrubN

I contemplated doing that too, however adding 5 null checks for a single null object is a bit excessive. Over time I have noticed some patterns with the Twitch GQL API that would let us confidently reduce it to 3 null checks, but that is still not 1.

By pulling the right strings, however, I think I have reliably reproduced the chapter issue within my REST client and will be writing a fix:
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/161d330f-45a0-48c3-a5e1-d91662b570d5)

**Comment by jmSfernandes** [comment]
> > From what I could gather these chapters are not really used anywhere apart from being serialized when the response is saved in Json (I believe for additional info) (e.g., In my use case, I think I don't need these `VideoChapters`... )
> 
> The video chapters are serialized to chat JSONs, however they are also used for encoding VOD chapters.
> 
> > I could make a PR to solve this with the nullity checks... but any advice on how to proceed with this @ScrubN
> 
> I contemplated doing that too, however adding 5 null checks for a single null object is a bit excessive. Over time I have noticed some patterns with the Twitch GQL API that would let us confidently reduce it to 3 null checks, but that is still not 1.
> 
> By pulling the right strings, however, I think I have reliably reproduced the chapter issue within my REST client and will be writing a fix: ![image](https://private-user-images.githubusercontent.com/72096833/290976295-161d330f-45a0-48c3-a5e1-d91662b570d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzY0MTAsIm5iZiI6MTcwMjczNjExMCwicGF0aCI6Ii83MjA5NjgzMy8yOTA5NzYyOTUtMTYxZDMzMGYtNDVhMC00OGMzLWE1ZTEtZDkxNjYyYjU3MGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzBjODFmMTdkMWY2YjU2Y2U1MzBlMzk4M2E2N2I5MTczMzNmY2RlY2JmYmIwN2UyNzMwOGIyZjZiNWI3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0nQJG-RXFTHRHojouVLgiaeS-fOXYWosQA7mZJOgAqA)

Thanks, much appreciated 🙌

**Comment by ScrubN** [comment]
The fix for the chapter crashes has been committed: bd4e98bc97b12e8fed3a184c7ebe6b08ae9a3421

As for the original concern of this issue, I would like to work on increasing the reliability of handling failures from the Twitch API, especially given that Twitch is destroying their backend really fast: 4e71e57537b0b9847d71d79d3782be324ba9875d b91f48fb3bf118b1b75985f248e9b818ca4c15a9 [dd2f583/M3U8.cs#L528-L533](https://github.com/lay295/TwitchDownloader/blob/dd2f583cf22478130c10a1ebcbeee85c88d6442d/TwitchDownloaderCore/Tools/M3U8.cs#L528-L533), but obviously that will take time to implement.
