### ISSUE TITLE
Crash when getting manifest

### ISSUE THREAD

**Issue by xiBread** [lay295/TwitchDownloader#776]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Any form of invocation triggers this exception. This is only happening with `1.53.1` (Mac).

```js
Unhandled exception. System.IO.FileNotFoundException: /Users/olv/.net/TwitchDownloaderCLI/3jQJ9qZTxGZ1ZSavbhQJVszmSUpplUc=/TwitchDownloaderCLI
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String )
   at TwitchDownloaderCLI.Program.GetManifestInfo()
   at TwitchDownloaderCLI.Program.<>c__DisplayClass1_0.<WriteHelpText>b__0(HelpText builder)
   at CommandLine.Text.HelpText.<>c__DisplayClass61_0`1.<AutoBuild>b__2(HelpText current)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Int32 maxDisplayWidth)
   at TwitchDownloaderCLI.Program.WriteHelpText(IEnumerable`1 errors, ParserResult`1 parserResult, ParserSettings parserSettings)
   at TwitchDownloaderCLI.Program.<>c__DisplayClass0_0.<Main>b__1(IEnumerable`1 errors)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by ScrubN** [comment]
Sorry about that, it seems .net on Mac works a little different. Should be fixed in the hotfix
