### ISSUE TITLE
Broken Clip Video Download Metadata on 1.53.2 

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#785]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Unable to download clips in the latest version.

```
/mnt/twitchvods2/twitch_vod_creator/thirdparty/Twitch_Downloader_1.53.2/TwitchDownloaderCLI clipdownload --id ChillyPlacidSpindleStrawBeary-0NP2f-FNpV7FGzNp --banner false  -o /tmp/tvc_render_clip_comp/ChillyPlacidSpindleStrawBeary-0NP2f-FNpV7FGzNp.mp4

[STATUS] - Fetching Clip Info
[STATUS] - Downloading Clip
[STATUS] - Encoding Clip MetadataUnhandled exception. System.AggregateException: One or more errors occurred. (Cannot start process because a file name has not been provided.)
 ---> System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at TwitchDownloaderCore.ClipDownloader.EncodeClipMetadata(String inputFile, String destinationFile, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ClipDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadClip.Download(ClipDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

Switching back to 1.53.0 seems to work as expected
```
/mnt/twitchvods2/twitch_vod_creator/thirdparty/Twitch_Downloader_1.53.0/TwitchDownloaderCLI clipdownload --id ChillyPlacidSpindleStrawBeary-0NP2f-FNpV7FGzNp -o /tmp/tvc_render_clip_comp/ChillyPlacidSpindleStrawBeary-0NP2f-FNpV7FGzNp.mp4
```

### Add any related files or extra information here

https://clips.twitch.tv/ChillyPlacidSpindleStrawBeary-0NP2f-FNpV7FGzNp

**Comment by ScrubN** [comment]
Yeah sorry I overlooked something. Just specific the ffmpeg path for now,
it's already fixed for the next release.

**Comment by goldbattle** [comment]
That fixed the issue, great!

**Comment by ScrubN** [comment]
https://github.com/lay295/TwitchDownloader/releases
