### ISSUE TITLE
One or more errors occurred. (Unable to parse decimal from: FRAME-RATE=59.994)

### ISSUE THREAD

**Issue by cyperdark** [lay295/TwitchDownloader#939]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

[TVD] System.AggregateException: One or more errors occurred. (Unable to parse decimal from: FRAME-RATE=59.994)
 ---> System.FormatException: Unable to parse decimal from: FRAME-RATE=59.994
   at TwitchDownloaderCore.Tools.M3U8.ParsingHelpers.ParseDecimalValue(ReadOnlySpan`1 text, ReadOnlySpan`1 keyName) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/Tools/M3U8.cs:line 744
   at TwitchDownloaderCore.Tools.M3U8.Stream.ExtStreamInfo.Parse(ReadOnlySpan`1 text) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/Tools/M3U8.cs:line 611
   at TwitchDownloaderCore.Tools.M3U8.ParseM3U8Key(ReadOnlySpan`1 text, Builder metadataBuilder, ExtMediaInfo& extMediaInfo, ExtStreamInfo& extStreamInfo, DateTimeOffset& extProgramDateTime, ExtByteRange& byteRange, ExtPartInfo& extPartInfo) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/Tools/M3U8.cs:line 148
   at TwitchDownloaderCore.Tools.M3U8.Parse(ReadOnlySpan`1 text, String basePath) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/Tools/M3U8.cs:line 113
   at TwitchDownloaderCore.VideoDownloader.GetQualityPlaylist(GqlVideoResponse videoInfo) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/VideoDownloader.cs:line 574
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(CancellationToken cancellationToken) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCore/VideoDownloader.cs:line 59
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Modes/DownloadVideo.cs:line 23
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args) in /home/runner/work/TwitchDownloader/TwitchDownloader/TwitchDownloaderCLI/Program.cs:line 33

### Add any related files or extra information here

F:/coding/vue/wip/cpol-v2.5/dashboard/.server/storage/TwitchDownloaderCLI.exe VideoDownload  --id 2023580460 --temp-path "C:/Users/user/Documents/cache" --ffmpeg-path "C:/ffmpeg/bin/ffmpeg.exe" -o "C:/Users/user/Downloads/1704603547_2023580460.mp4" -b 6636 -e 7178

**Comment by ScrubN** [comment]
Duplicate #933

Until the next version is released (tomorrow?), a workflow build of the patch can be found here: https://github.com/lay295/TwitchDownloader/actions/runs/7434637911
