### ISSUE TITLE
Unable to get info

### ISSUE THREAD

**Issue by cubroxx** [lay295/TwitchDownloader#96]
Getting an error since today, worked fine up until now. 

This is the error log:
ERROR: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderCore.TwitchHelper.<GetClipInfo>d__3.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderCore\TwitchHelper.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderWPF.PageClipDownload.<btnGetInfo_Click>d__2.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderWPF\PageClipDownload.xaml.cs:line 54

Not sure what this part is about, but that is definitely not me in case that matters: C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderCore\TwitchHelper.cs

![image](https://user-images.githubusercontent.com/74624194/99441438-b4ff4600-28cc-11eb-9d44-2931c2e4d91b.png)

**Comment by lay295** [comment]
Looks like twitch got rid of their old clips endpoint...
https://api.twitch.tv/kraken/clips/

So with the new Twitch API, I have to either have everyone login, or have a server in the middle handle API calls, lovely. I guess i'll just setup a cloudflare worker or something. The clips will be broken for a little bit until I get around to fixing it, thanks for the report.

**Comment by cubroxx** [comment]
Thanks a ton! You're the MVP

**Comment by lay295** [comment]
Well, I was gonna fix it now but it looks like that endpoint is working again. Maybe they accidentally turned it off for a bit? I don't see any announcements or discussions on the twitch dev forums saying that the endpoint was going to be removed. So for now I'm just gonna assume it was an error on Twitch's end and close this for now.

**Comment by cubroxx** [comment]
Can this be reopened? :( Keeps happening again since yesterday, still happening today
