### ISSUE TITLE
unable to get information (again)

### ISSUE THREAD

**Issue by cubroxx** [lay295/TwitchDownloader#97]
I commented in the closed ticket but to make sure this is being seen, the "unable to get information" error I reported 2 days ago keeps happening again. Started sometime yesterday and still isn't working

ERROR: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderCore.TwitchHelper.<GetClipInfo>d__3.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderCore\TwitchHelper.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderWPF.PageClipDownload.<btnGetInfo_Click>d__2.MoveNext() in C:\Users\Lewis Pardo\Documents\VisualStudioProjects\TwitchDownloaderWPF\TwitchDownloaderWPF\PageClipDownload.xaml.cs:line 54

![image](https://user-images.githubusercontent.com/74624194/99681857-7b951a80-2a33-11eb-8d38-7ff22809e123.png)

**Comment by notyemzy** [comment]
I just downloaded the program and i have the same issue.

**Comment by orbital00** [comment]
same issue

**Comment by lay295** [comment]
Should be fixed in 1.38
